### ISSUE TITLE
"local.scan" with two graphs

### ISSUE THREAD

**Issue by youngser** [igraph/xdata-igraph#20] opened 2014-01-13 17:00 UTC
```
set.seed(12345)
g1 <- erdos.renyi.game(n=20,p=0.1,directed=T)
g2 <- erdos.renyi.game(n=20,p=0.1,directed=T)
local.scan(g2,g1,k=1,mode="all",weighted=FALSE)
```

[1] 4.0 1.0 2.0 1.0 2.0 9.5 1.0 2.0 0.0 5.0 2.0 3.0 3.0 4.0 5.0 3.5 5.0 4.0 2.0
[20] 1.0

Note the non-integer numbers?
We believe that the correct numbers are
[1] 4 1 2 1 1 8 1 2 0 5 2 3 3 4 5 3 5 4 2 1

**Comment by gaborcsardi** [comment] 2014-01-13 18:29
OK, this is fixed now, but it would be nice to test all cases, i.e. mode="in", mode="out" as well.

**Closed as completed by gaborcsardi** 2014-01-13 18:29 UTC

**Comment by youngser** [comment] 2014-01-14 13:10
On Jan 13, 2014, at 1:29 PM, Gabor Csardi notifications@github.com wrote:

> OK, this is fixed now, but it would be nice to test all cases, i.e. mode="in", mode="out" as well.
> 
> I just tried v877, but it seems that the bug still remains:
> 
> set.seed(12345)
> g1 <- erdos.renyi.game(n=20,p=0.1,mode="all",directed=T)
> g2 <- erdos.renyi.game(n=20,p=0.1,mode="all",directed=T)
> local.scan(g2,g1,k=1,mode="all",weighted=FALSE)
>  [1] 4.0 1.0 2.0 1.0 2.0 9.5 1.0 2.0 0.0 5.0 2.0 3.0 3.0 4.0 5.0 3.5 5.0 4.0 2.0
> [20] 1.0

I believe the numbers should be:

> local.scan.jhu(g2,g1,k=1,mode="all",weighted=FALSE)
>  [1] 4 1 2 1 1 8 1 2 0 5 2 3 3 4 5 3 5 4 2 1

The "in" and "out" seems to be ok.

> sessionInfo()
> R version 3.0.2 (2013-09-25)
> Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_0.6.999-877

**Comment by gaborcsardi** [comment] 2014-01-14 17:33
Cannot reproduce, sorry. Are you sure your commands are coming from the same R session? Btw. the proper version string is printed by `igraph.version()`, but 0.6.999-877 seems to contain the fix.

**Comment by youngser** [comment] 2014-01-14 17:39
Oh, my bad.
It seems ok after restarting the R session.

> igraph.version()
> [1] "0.7.0-pre+877.dca5440"
